server:
  port: 9001
spring:
  application:
    name: auth-app
  datasource:
    username: root
    password: hjXL327918
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
  cloud:
    nacos:
      discovery:
        register-enabled: true
        server-addr: 127.0.0.1:8848
    compatibility-verifier:
      enabled: false
  thymeleaf:
    cache: false #这个开发配置为false，避免改了模板还要重启服务器
    encoding: utf-8 #编码字符集，默认为utf-8，可不用配置
  devtools:
    livereload:
      enabled: true
      port: 35731

debug: true

logging:
  level:
    root: info
    org.springframework:
      web: info
      security: info
      security.oauth2: info
      # spring boot 启动的时有大量的 CONDITIONS EVALUATION REPORT 信息，此处设置只打印 error 级别的信息
      boot.autoconfigure: error
      #web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
      security.web.FilterChainProxy: trace
      security.web.access.ExceptionTranslationFilter: trace
# Mybatis-plus
mybatis-plus:
  configuration:
    # 控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #mapper-locations: classpath:/mapper/*Mapper.xml

# swagger 访问地址: http://localhost:9001/swagger-ui/index.html
springdoc:
  api-docs:
    # 生产环境默认关闭API文档服务
    enabled: true

# 白名单配置(*:支持一层url, **:支持多层url)
whitelist:
  urls:
    # 自定义登录地址
    - "/login"
    # 临时白名单
#    - "/user/*"
    - "/user/test2"
    # AuthController 权限管理类白名单
    - "/auth/*"
    # swagger 白名单需要
    - "/swagger-ui/*"
    - "/swagger-ui.html"
    - "/v3/api-docs/**"
    # 本地静态资源过滤, * 标示当前目录下一层路径，** 表示多层
    - "/js/**"
    - "/css/**"
    - "/images/**"

