server:
  port: 9002

spring:
  application:
    name: provider-app
  datasource:
    username: root
    password: hjXL327918
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 配置 sentinel
#    sentinel:
#      transport:
#        dashboard: 127.0.0.1:8080




logging:
  level:
    root: info
    org.springframework:
      web: info
      security: info
      security.oauth2: info
      # spring boot 启动的时有大量的 CONDITIONS EVALUATION REPORT 信息，此处设置只打印 error 级别的信息
      boot.autoconfigure: error
      #      web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
      security.web.FilterChainProxy: trace # ???????
      security.web.access.ExceptionTranslationFilter: trace #????
springdoc:
  api-docs:
    enabled: true #开启/禁止api-docs,默认为true

